# Generated by Django 5.0.6 on 2024-08-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_notaire', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('num_mobile', models.CharField(max_length=20)),
                ('num_fixe', models.CharField(blank=True, max_length=20, null=True)),
                ('num_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('courriel', models.EmailField(max_length=254)),
                ('banque', models.CharField(choices=[('AGB', 'AGB'), ('Algérie Poste (CCP)', 'Algérie Poste (CCP)'), ('ASBA', 'ASBA'), ('B. ABC', 'B. ABC'), ('B. EL BARAKA', 'B. EL BARAKA'), ('BADR', 'BADR'), ('BDL', 'BDL'), ('BEA', 'BEA'), ('BN. HABITAT', 'BN. HABITAT'), ('BNA', 'BNA'), ('BNP PARIS BAS AL DJAZAIR', 'BNP PARIS BAS AL DJAZAIR'), ('CNEP', 'CNEP'), ('CPA', 'CPA'), ('FRANSABANK EL DJAZAIR', 'FRANSABANK EL DJAZAIR'), ('HBTF', 'HBTF'), ('HSBC', 'HSBC'), ('NATIXIS', 'NATIXIS'), ('SOCIETE GENERALE', 'SOCIETE GENERALE'), ('TBA', 'TBA')], max_length=255)),
                ('num_compte', models.CharField(blank=True, max_length=50, null=True)),
                ('autre', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.commune')),
            ],
        ),
    ]
