# Generated by Django 5.0.6 on 2024-08-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_notaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bailleur', models.CharField(max_length=255)),
                ('prenom_bailleur', models.CharField(max_length=255)),
                ('num_mobile', models.CharField(max_length=20)),
                ('num_fixe', models.CharField(blank=True, max_length=20, null=True)),
                ('num_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('courriel', models.EmailField(max_length=254)),
                ('banque', models.CharField(choices=[('AGB', 'AGB'), ('Algérie Poste (CCP)', 'Algérie Poste (CCP)'), ('ASBA', 'ASBA'), ('B. ABC', 'B. ABC'), ('B. EL BARAKA', 'B. EL BARAKA'), ('BADR', 'BADR'), ('BDL', 'BDL'), ('BEA', 'BEA'), ('BN. HABITAT', 'BN. HABITAT'), ('BNA', 'BNA'), ('BNP PARIS BAS AL DJAZAIR', 'BNP PARIS BAS AL DJAZAIR'), ('CNEP', 'CNEP'), ('CPA', 'CPA'), ('FRANSABANK EL DJAZAIR', 'FRANSABANK EL DJAZAIR'), ('HBTF', 'HBTF'), ('HSBC', 'HSBC'), ('NATIXIS', 'NATIXIS'), ('SOCIETE GENERALE', 'SOCIETE GENERALE'), ('TBA', 'TBA')], max_length=255)),
                ('num_compte', models.CharField(blank=True, max_length=50, null=True)),
                ('autre', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_site', models.CharField(max_length=100, unique=True)),
                ('nom_site', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('typologie', models.CharField(max_length=255)),
                ('surface_louee', models.FloatField()),
                ('propriete', models.CharField(choices=[('AADL', 'AADL'), ('ACED', 'ACED'), ('ADA', 'ADA'), ('ADE', 'ADE'), ('Aéroport', 'Aéroport'), ('Affaires Religieuses', 'Affaires Religieuses'), ('Algérie Poste', 'Algérie Poste'), ('Algérie Telecom', 'Algérie Telecom'), ('APC', 'APC'), ('ATM/ Mobilis', 'ATM/ Mobilis'), ('CABAM', 'CABAM'), ('Coloc OTA', 'Coloc OTA'), ('Coloc WTA', 'Coloc WTA'), ('Conservation des forêts', 'Conservation des forêts'), ('COSIDER', 'COSIDER'), ('Direction de la culture', 'Direction de la culture'), ('DJS', 'DJS'), ('Domaine', 'Domaine'), ('DOU/ Université', 'DOU/ Université'), ('EPSP', 'EPSP'), ('Exploitation Agricole', 'Exploitation Agricole'), ('GICA', 'GICA'), ('MDN', 'MDN'), ('Naftal', 'Naftal'), ('Privé', 'Privé'), ('Privé/ A. Commerciale', 'Privé/ A. Commerciale'), ('Protection Civile', 'Protection Civile'), ('Rail Telecom', 'Rail Telecom'), ('SCIMAT', 'SCIMAT'), ('SOGRAL', 'SOGRAL'), ('TDA', 'TDA'), ('Université', 'Université'), ('Wilaya', 'Wilaya'), ('Coloc OOREDO', 'Coloc OOREDO'), ('ColoC Djezzy', 'ColoC Djezzy')], max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bailleur')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.commune')),
                ('daira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.daira')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.wilaya')),
            ],
        ),
    ]
